// <auto-generated />
using LinkGenerator.Infrastructure.Data.DbConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkGenerator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LinkDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("LinkGenerator.Domain.Core.Links.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenerateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<long>("VisitCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("LinkId");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
